spring:
  application:
    name: AWS-Secrets-Manager-Demo
  config:
    import: "optional:arn:aws:secretsmanager:us-east-1:649089875063:secret:/AWS-Secrets-Manager-Demo/third-party-token*"

cloud:
  aws:
    region:
      static: us-east-1

watchmode:
  api-key: ${WATCHMODE_API_KEY:watchmode-api-key}
  base-url: https://api.watchmode.com/v1


